project:
  type: book
  output-dir: _book

book:
  title: "ALS Real World Evidence (RWE)"
  author: "Boyce Lab"
  description: "An interactive book for learning about RWE in ALS and Beyond."
  site-url: "https://alstdi.github.io/ALSRWE/"
  repo-url: "https://github.com/ALSTDI/ALSRWE"
  repo-branch: main
  repo-actions: [edit, issue]
  #favicon: images/favicon.ico  # Optional: Add your own favicon!
  search: true
  sidebar:
    style: docked
    search: true
    collapse-level: 2
    contents:
      - index.qmd
      - section: "Overview"
        contents:
          - approach.qmd
          - trainings.qmd
          - resources.qmd
      - section: "Data"
        contents:
          - GIS.qmd
          - ehr.qmd
     
format:
  html:
    theme:
      - cosmo
    css: styles.css  # Optional: Add a custom CSS!
    toc: true
    number-sections: true
    code-copy: true
    code-overflow: wrap

editor: visual
