name: Publish Quarto Book

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # prevent token issues

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # Optionally pin a version if you want
          version: "latest"

      - name: Install Pandoc (optional, if needed)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Render book
        run: quarto render
        continue-on-error: false  # fail fast if render fails

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
          publish_branch: gh-pages
